# Generated by Django 3.2 on 2023-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctors_N', models.CharField(max_length=200)),
                ('Doctors_Age', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=200)),
                ('Availability', models.CharField(max_length=100)),
                ('Visit_date', models.DateField()),
                ('Problem', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient_Pay_Tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Name', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Cost', models.FloatField()),
                ('Payment_type', models.CharField(max_length=200)),
                ('Payment_Status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Date_of_birth', models.DateField(max_length=200, null=True)),
                ('Last_visit', models.CharField(max_length=200, null=True)),
                ('Gender', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_No', models.IntegerField()),
                ('Room_Type', models.CharField(max_length=200)),
                ('Alt_dt', models.DateField()),
                ('Dis_dt', models.DateField()),
                ('Room_Status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
