# Generated by Django 3.2 on 2023-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20230428_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Cust_name',
            field=models.CharField(default=225456, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='Dr_dep',
            field=models.CharField(default=56456, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='Dr_name',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
